---
title: "Week 3"
date: "2/27/21"
author: "Masoumeh Khodaverdi"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Regular Expression

## **Problem 1**:

Started with this:

    First String    Second      1.22        3.4
    Second          More Text   1.555555    2.2220
    Third           x           3           124

Transformed to this:

    First String,Second,1.22,3.4
    Second,More Text,1.555555,2.2220
    Third,x,3,124

*By replacing `\t+ with \,`*

## **Problem 2**:

Started with this:

    Ballif, Bryan, University of Vermont
    Ellison, Aaron, Harvard Forest
    Record, Sydne, Bryn Mawr
      

Transformed to this:

    Bryan Ballif (University of Vermont)
    Aaron Ellison (Harvard Forest)
    Sydne Record (Bryn Mawr)

*By replacing `(\w+)\,\s(\w+)\,\s(.*) with \2 \1 \(\3\)`*

## **Problem 3**:

Started with this:

    0001 Georgia Horseshoe.mp3 0002 Billy In The Lowground.mp3 0003 Cherokee Shuffle.mp3 0004 Walking Cane.mp3

Transformed to:

    0001 Georgia Horseshoe.mp3
    0002 Billy In The Lowground.mp3
    0003 Cherokee Shuffle.mp3
    0004 Walking Cane.mp3

*By replacing `(.mp3)\s+ with \1\n`*

## **Problem 4**:

started with this:

    0001 Georgia Horseshoe.mp3
    0002 Billy In The Lowground.mp3
    0003 Cherokee Shuffle.mp3
    0004 Walking Cane.mp3

Transformed to:

    Georgia Horseshoe_0001.mp3
    Billy In The Lowground_0002.mp3
    Cherokee Shuffle_0003.mp3
    Walking Cane_0004.mp3

*By replacing
`(\w{4})\s(\w+\s\w+\s*\w*\s*\w*)(\.mp3) with \2_\1\3`*

## **Problem 5**:

Started with this:

    Camponotus,pennsylvanicus,10.2,44
    Camponotus,herculeanus,10.5,3
    Myrmica,punctiventris,12.2,4
    Lasius,neoniger,3.3,55

Transformed to this:

    C_pennsylvanicus,44
    C_herculeanus,3
    M_punctiventris,4
    L_neoniger,55

*By replacing`(\w)\w+\,(\w+)\,\d+\.\d+\,(\d+) with \1_\2,\3`*

## **Problem 6**:

Started with this:

    Camponotus,pennsylvanicus,10.2,44
    Camponotus,herculeanus,10.5,3
    Myrmica,punctiventris,12.2,4
    Lasius,neoniger,3.3,55

Transformed to this:

    C_penn,44
    C_herc,3
    M_punc,4
    L_neon,55

*By replacing`(\w)\w+\,(\w{4})\w+\,\d+\.\d+\,(\d+) with \1_\2,\3`*

## **Problem 7**:

Started with this:

    Camponotus,pennsylvanicus,10.2,44
    Camponotus,herculeanus,10.5,3
    Myrmica,punctiventris,12.2,4
    Lasius,neoniger,3.3,55

Transformed to this:

    Campen, 44, 10.2
    Camher, 3, 10.5
    Myrpun, 4, 12.2
    Lasneo, 55, 3.3

*By replacing `(\w{3})\w+,(\w{3})\w+,(\d+.\d),(\d+) with \1\2, \4, \3`*

[Return to Main Page](index.html)
